version: "3.7"
services:

  server-service:
    build: ./server-service
    expose:
      - "3000"
  
  client-service:
    build: ./client-service
    ports:
      - "3005:4000"
    expose:
      - "4000"

